name: Publish NuGet

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x' # Update to your .NET version

    - name: Create NuGet.Config
      run: |
        dotnet nuget add source --username not-required --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name InSciCo "https://nuget.pkg.github.com/InSciCo/index.json"
        cat > NuGet.Config << EOF
        <?xml version="1.0" encoding="utf-8"?>
        <configuration>
          <packageSourceMapping>
            <packageSource key="nuget.org">
              <package pattern="*" />
            </packageSource>
            <packageSource key="InSciCo">
              <package pattern="*" />
              <!-- Add other patterns as needed -->
            </packageSource>
          </packageSourceMapping>
        </configuration>
        EOF

    - name: Restore dependencies
      run: |
        dotnet restore

    - name: Build # Build solution
      run: dotnet build --no-restore

    - name: Publish
      run: |
        dotnet nuget push ./Packages/*.nupkg --source https://nuget.pkg.github.com/InSciCo/index.json --api-key ${{ secrets.GITHUB_TOKEN }}
        dotnet nuget push ./Packages/*.snupkg --source https://nuget.pkg.github.com/InSciCo/index.json --api-key ${{ secrets.GITHUB_TOKEN }}